raw_data_path: "E:/PROJECTS_FILE/CCP/data/raw/cell2celltrain.csv"
processed_data_path: "data/processed/cleaned_churn_data.csv"
model_dir: "models/"
model_path: "models/models/models\churn_pipeline.joblib"
target_column: "churn"
id_column: "customerid"
random_state: 42
test_size: 0.2

raw_data_path: "E:/PROJECTS_FILE/CCP/data/raw"

processed_data_path: "E:/PROJECTS_FILE/CCP/data/processed"

unknown_markers: ["Unknown", "?", "NA", "null", "none"]

categorical_columns:
  - "childreninhh"
  - "handsetrefurbished"
  - "handsetwebcapable"
  - "truckowner"
  - "rvowner"
  - "homeownership"
  - "buysviamailorder"
  - "respondstomailoffers"
  - "optoutmailings"
  - "nonustravel"
  - "ownsmotorcycle"
  - "madecalltoretentionteam"
  - "creditrating"
  - "prizmcode"
  - "occupation"
  - "maritalstatus"

numerical_columns:
  - "monthlyrevenue"
  - "monthlyminutes"
  - "totalrecurringcharge"
  - "directorassistedcalls"
  - "overageminutes"
  - "roamingcalls"
  - "percchangeminutes"
  - "percchangerevenues"
  - "droppedcalls"
  - "blockedcalls"
  - "unansweredcalls"
  - "customercarecalls"
  - "threewaycalls"
  - "receivedcalls"
  - "outboundcalls"
  - "inboundcalls"
  - "peakcallsinout"
  - "offpeakcallsinout"
  - "droppedblockedcalls"
  - "callforwardingcalls"
  - "callwaitingcalls"
  - "monthsinservice"
  - "uniquesubs"
  - "activesubs"
  - "handsets"
  - "handsetmodels"
  - "currentequipmentdays"
  - "agehh1"
  - "agehh2"
  - "retentioncalls"
  - "retentionoffersaccepted"
  - "referralsmadebysubscriber"
  - "incomegroup"
  - "adjustmentstocreditrating"